### ISSUE TITLE
Add (target =_blank) feature to IRC page "VIEW BLOG" buttons

### ISSUE THREAD

**Issue by akeel230** [sef-global/sef-site#1152] opened 2021-12-29 05:29 UTC
**Is your feature request related to a problem? Please describe.**
The view blog button on the IRC page redirects the user to another tab. We have to make them open the blogs in separate tabs to keep the user on our website.

**Describe the solution you'd like**
Add suitably attributes to the HTML code to give the functionality of opening the blogs in a new tab

**Describe alternatives you've considered**
Recommended target = _blank

**Additional context**
![Screenshot (704)](https://user-images.githubusercontent.com/83522139/147630248-6d333fb7-9f60-4d74-bd1b-fcd397dae974.png)

**Comment by maheshtamarakar** [comment] 2021-12-29 07:41
I would like to work can you assign it to me

**Comment by maheshtamarakar** [comment] 2021-12-29 08:25
I added the target = "_blank" in irc.htm anchor tag but because it has <tr onclick="window.location='{{linkedin}}';"> on the row of the table that irc.html page re-directed to LinkedIn profile, so what should I do about it? should I remove onclick="window.location='{{linkedin}}';". and view blog is opening in new page fine

**Comment by Piumal1999** [comment] 2021-12-29 08:34
> should I remove onclick="window.location='{{linkedin}}';"

@maheshtamarakar  Yeah, let's remove it and add the LinkedIn URL to the person’s name

**Comment by maheshtamarakar** [comment] 2021-12-29 10:43
ohk

**Comment by maheshtamarakar** [comment] 2021-12-29 10:48
so should I use cursor: pointer to person's name, and what should use style=" cursor: pointer;"  on td tag or should I make a separate class?

**Comment by Piumal1999** [comment] 2021-12-29 21:10
> so should I use cursor: pointer to person's name, and what should use style=" cursor: pointer;" on td tag or should I make a separate class?

I think we don't have to use additional styles. Adding an `<a>` tag with the LinkedIn URL would be enough. 

This is the expected behaviour:
If someone clicks on the person's name, the LinkedIn profile should be loaded in a new tab.
If someone clicks on the "View Blog" button, the blog page should load in a new tab.
If someone clicks anywhere else on the `<td>`, nothing should happen.

**Comment by maheshtamarakar** [comment] 2021-12-30 02:21
ok

**Comment by maheshtamarakar** [comment] 2021-12-30 02:28
adding a <a> will make the text color blue so is that ok?
If someone clicks on the person's name, the LinkedIn profile should be loaded in a new tab.-> done
If someone clicks on the "View Blog" button, the blog page should load in a new tab.->done
If someone clicks anywhere else on the <td>, nothing should happen.->done

**Comment by maheshtamarakar** [comment] 2021-12-30 02:35
or should I change the color using inline CSS or make a separate class

**Comment by akeel230** [comment] 2021-12-30 12:09
@maheshtamarakar please send a draft PR so that it will be easy to review the code and request changes if necessary. And thank you for the progress so far.

**Comment by Piumal1999** [comment] 2021-12-30 12:29
> adding a will make the text color blue so is that ok?

Yeah. It's ok

**Comment by maheshtamarakar** [comment] 2021-12-30 15:27
> @maheshtamarakar please send a draft PR so that it will be easy to review the code and request changes if necessary. And thank you for the progress so far.

glad I was helpful

**Comment by maheshtamarakar** [comment] 2021-12-30 15:46
> @maheshtamarakar please send a draft PR so that it will be easy to review the code and request changes if necessary. And thank you for the progress so far.

sent a draft PR

**Closed as completed** 2021-12-31 05:40 UTC
Labels: good first issue
